### ISSUE TITLE
Scrub does not accept size of 32

### ISSUE THREAD

**Issue by klundry** [joukos/PaperTTY#21]
Scrub states that you can specify a size between 8 and 32. It won't accept 32 but then tells you it must be 8-32.

`pi@raspberrypi:~/PaperTTY $ sudo ./papertty.py --driver epd2in13 scrub --size 32
Invalid stripe size, must be 8-32
`

**Comment by joukos** [comment]
Thanks, this is an actual bug - the range is not inclusive and I've apparently just slammed 32 there for the end. Will fix a bit later :)

**Comment by joukos** [comment]
Fixed in https://github.com/joukos/PaperTTY/commit/3f2f22d68f6b40428addf3bd5287824bc1429793
