### ISSUE TITLE
Replace PIL with Pillow

### ISSUE THREAD

**Issue by joukos** [joukos/PaperTTY#3]
This issue is for future reference.

@cclauss outlined some steps to replace the imaging library with Pillow in https://github.com/joukos/PaperTTY/issues/2#issuecomment-413100455.

Currently there's some wrinkles in going for it because the Waveshare library uses PIL. There are forks around already.

**Comment by cclauss** [comment]
A pointer to those forks please?

**Comment by joukos** [comment]
I probably won't have time to work on this for the rest of the week, but should use the repo above and make the necessary changes to instructions.

**Comment by cclauss** [comment]
Yes.  It would be a welcome addition if someday there were Python repos at https://github.com/waveshare

**Comment by joukos** [comment]
Fixed in 7e557abdc8a737d8f94e5eee1a07f802a85a572e.
