### ISSUE TITLE
Create PyPi package

### ISSUE THREAD

**Issue by joukos** [joukos/PaperTTY#44]
It would be very nice if it was possible to simplify the installation of PaperTTY to just `pip install papertty`. Any help with achieving this is appreciated.

**Comment by colin-nolan** [comment]
I'd be happy to take a look at this!

Unless you have an objection, I would setup the project with a `pyproject.toml` (as per PEP 518), which can be nicely managed with a tool such as [poetry](https://python-poetry.org/).

I suspect it will be easiest for `papertty.py` to be moved out of the root and into a new `papertty` package.

**Comment by joukos** [comment]
You're more than welcome to :) I almost started with this some time ago but didn't have time to do anything concrete.
