### ISSUE TITLE
Sudo with papertty?

### ISSUE THREAD

**Issue by Adam90a** [joukos/PaperTTY#75]
EDIT: sudo is working now, not sure what I did

I am stuck. I try to use sudo and get an error...

sudo papertty --driver EPD4IN2 terminal
sudo: papertty: command not found

...and without....

papertty --driver EPD4IN2 terminal
Loading PIL font /home/pi/.local/lib/python3.7/site-packages/papertty/resources/tom-thumb.pil. Font size is ignored.
No read access to /dev/vcsa1 - maybe run with sudo?

.....any suggestions?

**Comment by Julian-MJK** [comment]
Dear god if you fixed this, tell us how, don't just close the damn issue so that nobody who has the same issue in the future can figure it out

**Comment by Mozartenhimer** [comment]
This looks like a cli usage thing. It's likely that '. (current directory)
is not on the path for root,  it is for the user invoking sudo. The
solution for running it under sudo on this instance would be:
sudo  ./papertty

**Comment by gridbasedotnet** [comment]
Did you ever get this resolved?

**Comment by Adam90a** [comment]
Nope, gave up
