### ISSUE TITLE
Standalone Guidance

### ISSUE THREAD

**Issue by jacobjozwiak** [joukos/PaperTTY#79]
Hi, let me just say that this project is amazing. I have managed to get vnc working and now would now like to run it in standalone mode. I have a mouse and keyboard plugged into the rpi. I also have a 7" screen plugged in (which I'm hoping to get rid of). My question is how do I go about creating an interactive session when there will be no physical screen connected to the rpi for it to "shadow"? And how can I configure the screen to be the same resolution as my eink display (I'm running a 10.3 inch)?

I hope that makes sense. Any guidance is appreciated. 

Thanks again for your hard work!

**Comment by Doodke3** [comment]
Have you figured out how?
