### ISSUE TITLE
is theare a option like rotate in terminal ?

### ISSUE THREAD

**Issue by huangmingyou** [joukos/PaperTTY#84]
I had run PaperTTY on a 10.3 waveshare epaper, the terminal command work fine.  but I can't rotate the display.

**Comment by joukos** [comment]
A more proper rotation command is sort of pending for me to dig an old branch of mine that had some changes to implement a framebuffer and such and I think I implemented it partly, but haven't had time to wrap it up. There is a `--portrait` option for the `terminal` command though, if that works.
